### ISSUE TITLE
Remove `Test.sol` and `TestOwner.sol`

### ISSUE THREAD

**Issue by Sabnock01** [base-org/contracts#49]
It doesn't appear that either of these contracts are being used anywhere? Can they be removed?
- [`Test.sol`](https://github.com/base-org/contracts/blob/main/src/Test.sol)
- [`TestOwner.sol`](https://github.com/base-org/contracts/blob/main/src/TestOwner.sol)

**Comment by wbnns** [comment]
@Sabnock01 

Hi there! Thanks for reaching out and opening this issue. Will add this to our backlog so one of the team members can take a closer look! 🤝

**Comment by Sabnock01** [comment]
> @Sabnock01 
> 
> Hi there! Thanks for reaching out and opening this issue. Will add this to our backlog so one of the team members can take a closer look! 🤝 

Thanks! Am fine with opening the PR myself in the event you guys want to proceed.

**Comment by anikaraghu** [comment]
@Sabnock01 We often use the contracts from this repo in https://github.com/base-org/contract-deployments - the smart contract files you pointed out are sometimes used in that repo for testing.
